[package]
name = "pt-data"
edition.workspace = true
version.workspace = true

[dependencies]
pt-domain = { workspace = true }
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
thiserror = { workspace = true }

[features]
bundled = []

[build-dependencies]
serde = { workspace = true }
serde_yaml_ng = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
