[package]
name = "pt-wasm"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pt-services = { workspace = true, features = ["bundled"] }
pt-domain = { workspace = true }
wasm-bindgen = "0.2"
tsify = { version = "0.4", features = ["js"] }
serde = { workspace = true }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3"
